"""Add topics table and update flashcards

Revision ID: 2fb3a29a451f
Revises: c52fc3d85fcb
Create Date: 2026-04-20 18:18:26.599699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fb3a29a451f'
down_revision: Union[str, Sequence[str], None] = 'c52fc3d85fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_predefined', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_name'), ['name'], unique=True)

    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example_sentence', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('topic_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_flashcards_topic_id'), ['topic_id'], unique=False)
        batch_op.create_foreign_key('fk_flashcards_topic_id', 'topics', ['topic_id'], ['id'])

    # ### end Alembic commands ###
    
    # Seed topics
    import uuid
    
    topics_to_seed = [
        "SCHOOL", "LEISURE ACTIVITIES", "WORK", "SPORT AND GAME", "EDUCATION",
        "FOOD AND DRINK", "FAMILY", "TOURISM", "LIFESTYLE", "TRANSPORTATION",
        "GENDER EQUALITY", "CULTURE", "VOLUNTEERING", "NATURE AND ENVIRONMENT",
        "THE MEDIA", "SCIENCE AND TECHNOLOGY", "PHYSICAL APPEARRANCE AND PERSONALITY",
        "URBANISATION", "THE GREEN MOVEMENT", "FILM", "COUNTRY AND CITY LIFE",
        "RELATIONSHIP", "PLACES AND WONDERS", "HEALTH", "COMMUNITY SERVICE",
        "MUSIC AND ART", "SPACE AND OTHER PLANETS", "CRIME AND PUNISHMENT",
        "HOLIDAYS AND FESTIVALS", "CUSTOMS AND TRADITIONS", "VSTEP READING"
    ]
    
    # We'll use a mapping of name to id for the flashcard update
    topic_mapping = {}
    for name in topics_to_seed:
        topic_id = uuid.uuid4()
        topic_mapping[name] = topic_id
        # op.execute doesn't support bindparams in the same way as sqlalchemy connection in all alembic versions
        # but sa.text with bindparams is usually safe.
        # However, for SQLite and simpler op.execute:
        op.execute(
            sa.text("INSERT INTO topics (id, name, is_predefined) VALUES (:id, :name, 1)")
            .bindparams(id=topic_id, name=name)
        )
    
    # Update existing flashcards to use "VSTEP READING"
    vstep_reading_id = topic_mapping["VSTEP READING"]
    op.execute(
        sa.text("UPDATE flashcards SET topic_id = :topic_id")
        .bindparams(topic_id=vstep_reading_id)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flashcards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_flashcards_topic_id'))
        batch_op.drop_column('topic_id')
        batch_op.drop_column('example_sentence')

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_name'))

    op.drop_table('topics')
    # ### end Alembic commands ###
